name: sport
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Bloc
  bloc:
  flutter_bloc:

  # Freezed
  freezed_annotation: ^0.14.0

  # Audio
  assets_audio_player: ^3.0.3+1
  flutter_tts: ^3.1.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Freezed
  build_runner:
  freezed: ^0.14.0
  json_serializable:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/exercises.json
    - assets/workouts.json
    - assets/images/Arms/Superman/
    - assets/images/Arms/Hammer Curls/
    - assets/images/Arms/Arm Circle/
    - assets/images/Arms/Bear Crawl/
    - assets/images/Arms/Push Up/
    - assets/images/Arms/Hip Hinge High Plank/
    - assets/images/Arms/Side Plank Needle/
    - assets/images/Arms/Mountain Climber/
    - assets/images/Arms/Rear Delt Flies/
    - assets/images/Arms/Reverse Fly/
    - assets/images/Arms/Plank/
    - assets/images/Arms/Burpee/
    - assets/images/Arms/Shoulder Lift/
    - assets/images/Arms/Supinated Biceps Curls/
    - assets/images/Arms/Zottman Curls/
    - assets/images/Arms/Pronated Curls/
    - assets/images/Bottom/
    - assets/images/Bottom/Lateral Lunge/
    - assets/images/Bottom/Bridge Walkout/
    - assets/images/Bottom/Bridge/
    - assets/images/Bottom/Curtsy Lunge/
    - assets/images/Bottom/Lunges/
    - assets/images/Bottom/Squat Hold Abduction/
    - assets/images/Bottom/Single Leg Bridge/
    - assets/images/Bottom/Pulsing Squat/
    - assets/images/Bottom/Side Lying Abduction/
    - assets/images/Bottom/Crab Walk/
    - assets/images/Bottom/Kneeling Squat/
    - assets/images/Bottom/Gluteus Kickback/
    - assets/images/Triceps/
    - assets/images/Triceps/Bench Press Alternating/
    - assets/images/Triceps/Triceps Kickback/
    - assets/images/Triceps/Dips/
    - assets/images/Triceps/Bench Press/
    - assets/images/Triceps/Overhead Triceps Extension/
    - assets/images/Triceps/Close Triceps Extension/